name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar ambiente de deploy
        run: echo "Preparando para o deploy"

      - name: Deploy para o servidor
        run: |
          scp -r ./meu-app user@server:/caminho/do/deploy
